In [ ]:
!pip install transformers==4.46.0
!pip install tf-keras
!pip install bertviz

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.1/44.1 kB 1.5 MB/s eta 0:00:00
Reason for being yanked: This version unfortunately does not work with 3.8 but we did not drop the support yet
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 67.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 27.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 73.5 MB/s eta 0:00:00
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface_hub 1.20.1
    Uninstalling huggingface_hub-1.20.1:
      Successfully uninstalled huggingface_hub-1.20.1
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.22.2
    Uninstalling tokenizers-0.22.2:
      Successfully uninstalled tokenizers-0.22.2
  Attempting uninstall: transformers
    Found existing installation: transformers 5.12.1
    Uninstalling transformers-5.12.1:
      Successfully uninstalled transformers-5.12.1
ERROR: pip's dependency resolve

In [ ]:
import os
os.environ['TF_USE_LEGACY_KERAS']='1'
import tf_keras
#Importing required libraries
import tensorflow as tf
import torch
import nltk
import pandas as pd
import matplotlib.pyplot as plt

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

from transformers import (
    BertTokenizer,
    BertModel,
    BertForMaskedLM,
    TFBertForSequenceClassification,
    pipeline
)
from bertviz import head_view


In [ ]:
#Download nltk data
nltk.download('punkt')
nltk.download('stopwords')


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
#Stopword set
sw=set(stopwords.words('english'))
txt_arr=[
    "The coffee machine stopped working after two days",
    "I absolutely loved the soundtrack of this series",
    "The train reached exactly at the scheduled time",
    "The keyboard keys feel smooth and comfortable",
    "The soup tasted stale and unpleasant",
    "My internet speed has been stable all week",
    "The smartwatch display looks very sharp",
    "The lecture today was neither boring nor exciting",
    "The shoe sole came off within a month",
    "The park was quiet during the evening"
]


In [ ]:
lb = [1,0,2,1,0,2,1,2,0,2]

In [ ]:
tk=BertTokenizer.from_pretrained('bert-base-uncased')

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
clr_txt=[]
for sent in txt_arr:
    wrd=word_tokenize(sent.lower())
    tmp=[]
    for j in wrd:
        if j not in sw:
            tmp.append(j)
    clr_txt.append(tmp)


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
#Print cleaned text
print("After removing stopwords:\n")
for i in clr_txt:
    print(i)

After removing stopwords:

['coffee', 'machine', 'stopped', 'working', 'two', 'days']
['absolutely', 'loved', 'soundtrack', 'series']
['train', 'reached', 'exactly', 'scheduled', 'time']
['keyboard', 'keys', 'feel', 'smooth', 'comfortable']
['soup', 'tasted', 'stale', 'unpleasant']
['internet', 'speed', 'stable', 'week']
['smartwatch', 'display', 'looks', 'sharp']
['lecture', 'today', 'neither', 'boring', 'exciting']
['shoe', 'sole', 'came', 'within', 'month']
['park', 'quiet', 'evening']


In [ ]:
print("BERT Tokens:")
for s in txt_arr:
    enc=tk.tokenize(s)
    print(enc)


BERT Tokens:
['the', 'coffee', 'machine', 'stopped', 'working', 'after', 'two', 'days']
['i', 'absolutely', 'loved', 'the', 'soundtrack', 'of', 'this', 'series']
['the', 'train', 'reached', 'exactly', 'at', 'the', 'scheduled', 'time']
['the', 'keyboard', 'keys', 'feel', 'smooth', 'and', 'comfortable']
['the', 'soup', 'tasted', 'stale', 'and', 'unpleasant']
['my', 'internet', 'speed', 'has', 'been', 'stable', 'all', 'week']
['the', 'smart', '##watch', 'display', 'looks', 'very', 'sharp']
['the', 'lecture', 'today', 'was', 'neither', 'boring', 'nor', 'exciting']
['the', 'shoe', 'sole', 'came', 'off', 'within', 'a', 'month']
['the', 'park', 'was', 'quiet', 'during', 'the', 'evening']


In [ ]:
x=tk(txt_arr,padding=True,truncation=True,return_tensors='tf')

print("Input IDs:")
print(x['input_ids'])


Input IDs:
tf.Tensor(
[[  101  1996  4157  3698  3030  2551  2044  2048  2420   102]
 [  101  1045  7078  3866  1996  6050  1997  2023  2186   102]
 [  101  1996  3345  2584  3599  2012  1996  5115  2051   102]
 [  101  1996  9019  6309  2514  5744  1998  6625   102     0]
 [  101  1996 11350 12595 26729  1998 16010   102     0     0]
 [  101  2026  4274  3177  2038  2042  6540  2035  2733   102]
 [  101  1996  6047 18866  4653  3504  2200  4629   102     0]
 [  101  1996  8835  2651  2001  4445 11771  4496 10990   102]
 [  101  1996 10818  7082  2234  2125  2306  1037  3204   102]
 [  101  1996  2380  2001  4251  2076  1996  3944   102     0]], shape=(10, 10), dtype=int32)


In [ ]:
bert_m=BertModel.from_pretrained('bert-base-uncased',output_attentions=True)

for line in txt_arr[:2]:
    ip=tk(line, return_tensors='pt')
    op=bert_m(**ip)
    attn=op.attentions
    tok=tk.convert_ids_to_tokens(ip['input_ids'][0])
    head_view(attn, tok)


model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

BertSdpaSelfAttention is used but `torch.nn.functional.scaled_dot_product_attention` does not support non-absolute `position_embedding_type` or `output_attentions=True` or `head_mask`. Falling back to the manual attention implementation, but specifying the manual implementation will be required from Transformers version v5.0.0 onwards. This warning can be removed using the argument `attn_implementation="eager"` when loading the model.


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
mk=pipeline("fill-mask",model="bert-base-uncased")
msk_sent="The movie was [MASK]"
res=mk(msk_sent)

print("Masked Word Predictions:")
for r in res:
    print(r['token_str'], ":", r['score'])


BertForMaskedLM has generative capabilities, as `prepare_inputs_for_generation` is explicitly overwritten. However, it doesn't directly inherit from `GenerationMixin`. From 👉v4.50👈 onwards, `PreTrainedModel` will NOT inherit from `GenerationMixin`, and this model will lose the ability to call `generate` and other related functions.
  - If you're using `trust_remote_code=True`, you can get rid of this warning by loading the model with an auto class. See https://huggingface.co/docs/transformers/en/model_doc/auto#auto-classes
  - If you are the owner of the model architecture code, please modify your model class such that it inherits from `GenerationMixin` (after `PreTrainedModel`, otherwise you'll get an exception).
  - If you are not the owner of the model architecture class, please contact the model code owner to update it.
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'c

Masked Word Predictions:
. : 0.7416006326675415
! : 0.10419832170009613
; : 0.09899189323186874
? : 0.04687131941318512
| : 0.004540933296084404


In [ ]:
txt1="The camera quality is excellent"
ip2=tk(txt1, return_tensors='pt')
op2=bert_m(**ip2)
att=op2.attentions
tok2=tk.convert_ids_to_tokens(ip2['input_ids'][0])
ly=0
hd=0
mat=att[ly][0][hd].detach().numpy()
df=pd.DataFrame(mat, columns=tok2, index=tok2)

print("Attention Matrix Dataframe:")
print(df)


Attention Matrix Dataframe:
              [CLS]       the    camera   quality        is  excellent  \
[CLS]      0.085047  0.193101  0.074128  0.042603  0.069930   0.091741   
the        0.141198  0.151093  0.125808  0.081067  0.178776   0.189071   
camera     0.098050  0.094243  0.114748  0.185544  0.142427   0.200969   
quality    0.193325  0.034455  0.151161  0.083852  0.254379   0.137132   
is         0.190672  0.052113  0.111172  0.145818  0.191876   0.238926   
excellent  0.059100  0.065431  0.158965  0.199615  0.131568   0.186354   
[SEP]      0.165865  0.172010  0.083870  0.070329  0.133574   0.133354   

              [SEP]  
[CLS]      0.443449  
the        0.132987  
camera     0.164019  
quality    0.145695  
is         0.069423  
excellent  0.198967  
[SEP]      0.240998  


In [ ]:
mdl=TFBertForSequenceClassification.from_pretrained('bert-base-uncased',num_labels=3)

All PyTorch model weights were used when initializing TFBertForSequenceClassification.

Some weights or buffers of the TF 2.0 model TFBertForSequenceClassification were not initialized from the PyTorch model and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
opt=tf.keras.optimizers.Adam(learning_rate=3e-5)

In [ ]:
mdl.compile(
    optimizer=opt
)


In [ ]:
y=tf.constant(lb)

mdl.fit(
    {
        'input_ids': x['input_ids'],
        'attention_mask': x['attention_mask']
    },
    y,
    epochs=15
)


Epoch 1/15
1/1 [==============================] - 54s 54s/step - loss: 1.0652
Epoch 2/15
1/1 [==============================] - 2s 2s/step - loss: 1.0156
Epoch 3/15
1/1 [==============================] - 3s 3s/step - loss: 0.9708
Epoch 4/15
1/1 [==============================] - 4s 4s/step - loss: 0.9293
Epoch 5/15
1/1 [==============================] - 3s 3s/step - loss: 0.9558
Epoch 6/15
1/1 [==============================] - 2s 2s/step - loss: 0.8394
Epoch 7/15
1/1 [==============================] - 2s 2s/step - loss: 0.8495
Epoch 8/15
1/1 [==============================] - 3s 3s/step - loss: 0.7807
Epoch 9/15
1/1 [==============================] - 4s 4s/step - loss: 0.7338
Epoch 10/15
1/1 [==============================] - 3s 3s/step - loss: 0.7067
Epoch 11/15
1/1 [==============================] - 3s 3s/step - loss: 0.6034
Epoch 12/15
1/1 [==============================] - 3s 3s/step - loss: 0.5864
Epoch 13/15
1/1 [==============================] - 5s 5s/step - loss: 0.5522
Epoch 

In [ ]:
test=["The smartwatch display is amazing"]

test_ip=tk(test,padding=True,truncation=True,return_tensors='tf')

prd=mdl.predict(dict(test_ip))
cls=tf.argmax(prd.logits, axis=1).numpy()[0]

sent_map = {0: "Negative",1: "Positive",2: "Neutral"}

print("Predicted Sentiment :")
print(sent_map[cls])


1/1 [==============================] - 4s 4s/step
Predicted Sentiment :
Positive
